---
language: bash

before_install:
  - git clone https://github.com/bats-core/bats-core.git $HOME/bats-core

before_script:
  - export PATH="$HOME/bats-core/bin:${PATH}"

script:
  - bash run lint
  - bash run test
