---
language: bash

before_install:
  - git clone https://github.com/sstephenson/bats.git ../bats
  - ../bats/install.sh $HOME/.local/bin

before_script:
  - export PATH="$HOME/.local/bin:${PATH}"

script:
  - bash run lint
  - bash run test
