#!/usr/bin/env bash

# Defined scripts.
function lint() {
	_check_binaries "shellcheck"
	shellcheck --format=tty --shell=sh ./**/*.sh
}

function test() {
	_check_binaries "bats"
	find . -iname "*.bats" -exec sh -c "bats {}" ";"
}

function format() {
	_check_binaries "shfmt"
	find . -iname "*.sh" -exec sh -c "shfmt -bn -ci -w {}" ";"
}

function watch() {
	_check_binaries "entr"
	find . -type f -iname "*.sh" -o -iname "*.bats" | entr -c bash run check
}

function check() {
	lint
	test
}

# Don't go down here.
set -e

# Check binaries.
function _check_binaries() {
	for i in "$@"; do
		[ -x "$(command -v "$i")" ] || {
			echo "bats is required" >&2
			exit 1
		}
	done
}

# Check for scripts.
[ -n "$1" ] || {
	echo "first argument is mandatory" >&2
	exit 1
}

[ -n "$(declare -f -F $1)" ] || {
	echo "script unrecognized" >&2
	exit 1
}

# Run script.
eval "$@"
