#!/usr/bin/env bash

# Defined scripts.
function lint() {
	shellcheck --format=tty --shell=sh ./**/*.sh
}

function test() {
	find . -name "*.bats" -exec sh -c "bats {}" ";"
}

function check() {
  lint
  test
}

# Don't go down here.
set -e

# Check binaries.
[ -x "$(command -v shellcheck)" ] || {
	echo "shellcheck is required" >&2
	exit 1
}
[ -x "$(command -v bats)" ] || {
	echo "bats is required" >&2
	exit 1
}

# Check for scripts.
[ -n "$1" ] || {
  echo "first argument is mandatory" >&2
  exit 1
}

[ -n "$(declare -f -F $1)" ] || {
  echo "script unrecognized" >&2
  exit 1
}

# Run script.
eval "$@"
